version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - GOARCH=amd64 GOOS=linux go build -o bin/linux/txbox
      - GOARCH=amd64 GOOS=darwin go build -o bin/darwin/txbox
      - GOARCH=amd64 GOOS=windows go build -o bin/windows/txbox
      - zip -r bin bin
      - echo Build completed on `date`
artifacts:
  files:
    - bin.zip