version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - echo Build started on `date`
      # - echo Getting packages
      # - go get ./...
      - echo Compiling the Go code...
      - go build
      - echo Build completed on `date`
  # post_build:
  #   commands:
artifacts:
  files:
    - testbox