name: Publish binaries on release
on: release
jobs:
  build_and_release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, windows, linux]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          mkdir -p bin/${{ matrix.goos }}
          go build -o bin/${{ matrix.goos }}

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}