name: Publish binaries on release
on: release
jobs:
  build_and_release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, windows, linux]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          mkdir -p ${{ matrix.goos }}
          go build -o ${{ matrix.goos }}
          zip -r ${{ matrix.goos }}-amd64-${{ github.event.release.tag_name }} ${{ matrix.goos }}
          ls -la

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ${{ matrix.goos }}-amd64-${{ github.event.release.tag_name }}.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}