name: Publish binaries on release
on: release
jobs:
  build_and_release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: mkdir -p ${{ matrix.os }}/bin && go build -o ${{ matrix.os }}/bin
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: amd64

      - name: Release
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}-testbox
          path: ${{ matrix.os }}/bin/testbox
