name: Publish binaries on release
on: release
jobs:
  build_and_release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, windows, linux]
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          mkdir -p bin/${{ matrix.goos }}
          go build -o bin/${{ matrix.goos }}

      - name: Release
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.goos }}-testbox
          path: bin/${{ matrix.goos }}/testbox
